name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0/10 * * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: kitty
        
